### ISSUE TITLE
codestyle - White space and 80  character line limit 

### ISSUE THREAD

**Issue by Tallion-07** [Tallion-07/I3d-Import-Export-Giants#9]
## task list
- [x] _init_.py
- [x] i3d_IO_export.py
- [x] i3d_UIexport.py
- [x] i3d_Export.py
- [x] i3d_ui.py
- (dcc)
 - [x] _init_.py
 - [x] dccBlender.py

**Comment by ssnd292** [comment]
Just commentin here - But do you still plan on keeping this updated?

**Comment by Tallion-07** [comment]
yes , I do plan too, unfortunately the more people power the faster or easier it will be to keep maintained and up to date, even having people posting problems they are having will keep all the issues and bugs in one place, there may be no "quick fix" but at least whoever works on this doesn't have to go trolling all over the internet to see what needs updating or patching, so far I am the only one working on it but i have seen has forked the project as well, so hopefully interest and assistance maybe slowly increasing. thanks for posting

**Comment by StjerneIdioten** [comment]
I am looking a bit at it as well (hence the fork), but my time is rather sparse at the moment. I chatted a bit with a guy on the GDN, who had corrected the code so it at least worked with Blender 2.8, but he did warn me that the code itself is way old and back from the FS 2013 days. So it probably needs a bigger rewrite.

**Comment by Tallion-07** [comment]
I agree with what you are saying, even though I do not have a great deal of python programming experience, just through the plug in's with visual studio code, and what it is generating as error's out of those, and checking out briefly information on the errors, i think the code was written originally in python 1.6 or something, so the plugin code base hasn't been updated in ages, and because of some errors that came up, i wouldn't be surprised that some of the functions within the plugin were not even working. thats why in the project area I have listed a code review as part of the process. as you said it may need even a complete re write and re-organisation of the code, to even make it easier to follow the code and its sections and purposes. I am starting at documenting some of the code areas, and creating part of the wiki for the current and future contributing programmers and a seperate users part of the wiki.

**Comment by Tallion-07** [comment]
@StjerneIdioten you may need to redo your branch or do a new one, I apologise profusely as I mistakenly deleted it, and by the time I had realised what i had done, it was too late to restore it.
many apologies
